### ISSUE TITLE
Support for the new Opaque API?

### ISSUE THREAD

**Issue by franchb** [favadi/protoc-go-inject-tag#67]
This tool breaks on the new Protobuf Opaque API https://go.dev/blog/protobuf-opaque :

```shell
goroutine 1 [running]:
main.parseFile({0x7ffd635be5c9, 0x26}, {0x0, 0x0}, {0x0, 0x0, 0xf?})
        /home/user/go/pkg/mod/github.com/favadi/protoc-go-inject-tag@v1.4.0/file.go:116 +0xa49
main.main()
        /home/user/go/pkg/mod/github.com/favadi/protoc-go-inject-tag@v1.4.0/main.go:56 +0x425

find proto/echelon -name '*.pb.go' -exec tools/bin/protoc-go-inject-tag -input="{}" \;
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ff549]

goroutine 1 [running]:
main.parseFile({0x7fffe1d345c9, 0x26}, {0x0, 0x0}, {0x0, 0x0, 0xf?})
        /home/user/go/pkg/mod/github.com/favadi/protoc-go-inject-tag@v1.4.0/file.go:116 +0xa49
main.main()
        /home/user/go/pkg/mod/github.com/favadi/protoc-go-inject-tag@v1.4.0/main.go:56 +0x425
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ff549]

```

**Comment by NSKryukov** [comment]
Do we have any workaround ?

**Comment by favadi** [comment]
I haven't had time to look at this yet, but I'll happy to merge a PR if someone provided a solution.

**Comment by benjfield** [comment]
I believe this should fix this problem:

https://github.com/favadi/protoc-go-inject-tag/pull/71

Its worth noting that while this allows support for the hybrid style, opaque api explicitly doesnt have any exported fields by design which would seemingly make having tags fairly pointless.

**Comment by franchb** [comment]
I've implemented a better way of making it in modern Protobuf

https://github.com/franchb/protoc-gen-go-fieldmeta
